<?php

namespace AppBundle\Repository;

/**
 * ToolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolsRepository extends \Doctrine\ORM\EntityRepository
{
}
